
# Redirect any URLs with the default language code in them already
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/en/*"
  to = "/404/index.html"
  status = 404

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
