name: Build and Deploy to Netlify

on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35

      - name: Check for non-Markdown files
        id: check_files
        run: |
          non_markdown_files=$(echo "${{ steps.changed_files.outputs.modified_files }}" | grep -v '\.md$' || true)
          echo "non_markdown_files=$non_markdown_files" >> $GITHUB_OUTPUT

      - name: Build site
        id: build_site
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || -n "${{ steps.check_files.outputs.non_markdown_files }}" ]]; then
            npm install
            npm run build
            echo "result=built" >> $GITHUB_OUTPUT
          else
            echo "Skipping build step."
            echo "result=skipped" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Netlify
        if: steps.build_site.outputs.result == 'built'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          netlify-config-path: ./netlify.toml
          production-branch: main
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
