name: Build and Deploy to Cloudflare Pages

on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches:
      - main
      - switch-to-cf-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35

      - name: Check for non-Markdown files
        id: check_files
        run: |
          non_markdown_files=$(echo "${{ steps.changed_files.outputs.modified_files }}" | grep -v '\.md$' || true)
          echo "non_markdown_files=$non_markdown_files" >> $GITHUB_OUTPUT

      - name: Build site
        id: build_site
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "workflow_dispatch" || -n "${{ steps.check_files.outputs.non_markdown_files }}" ]]; then
            npm install
            npm run build
            echo "result=built" >> $GITHUB_OUTPUT
          else
            echo "Skipping build step."
            echo "result=skipped" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ./dist
