name: Netlify builds

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [created, updated, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with: 
          version: 12.x
          
      - name: Build site
        working-directory: ./
        run: |
          npm install --production
          npm run build
          
      - name: Netlify deployment      
        uses: nwtgck/actions-netlify@v1.1.11      
        with:
          publish-dir: './dist'
          production-branch: main 
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
